# Mocha config for integration tests.
require:
  - source-map-support/register
file:
  - dist/mjs/test-utils/setup/all.js
  - dist/mjs/test-utils/setup/integration.js
reporterOption:
  - 'maxDiffSize=0'
